version: '3'

services:
  mynginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: mynginx
    networks:
      - node-network
    tty: true
    ports:
      - "8080:8080"  
    depends_on:
      - mynode

  mynode:
    build: 
      context: ./node
      dockerfile: Dockerfile.prod
    image: mynode
    container_name: mynode
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 30s && node index.js"
    tty: true
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge